zuul:
  routes:
    auth:
      path: /auth-service/**
      serviceId: auth-service
    chat:
      path: /chat-service/**
      serviceId: chat-service

#default to 200 and 20 respectively.
#zuul.host.maxTotalConnections=200
#zuul.host.maxPerRouteConnections=20
#ribbon.eureka.enabled=false
server:
  port: 8080